site_name: SimpleKotlinMail

theme:
  name: mkdocs
  hljs_languages:
    - kotlin
    - groovy
  hljs_style: atom-one-light

nav:
  - Home: index.md
  - Setup:
    - Setup using Gradle: setup_gradle.md
  - Server: server.md
