site_name: SimpleKotlinMail
site_description: A simple, modern and coroutine based Kotlin Email API, supporting both clientside and serverside projects
site_author: Jakob K
copyright: © Copyright (2021) - Jakob K

theme:
  name: mkdocs
  hljs_languages:
    - kotlin
    - groovy
  hljs_style: atom-one-light

nav:
  - Home: index.md
  - Setup:
      - Setup using Gradle: setup_gradle.md
      - Setup using Maven: setup_maven.md
  - Core:
      - Email API: core.md
      - Kotlin HTML DSL: html.md
      - Convert: convert.md
  - Server: server.md
  - Client: client.md
  - TLS: tls.md
